[parser]
separators = [",", ";", "/", "&"]
feat_keywords = ["feat.", "ft.", "feat", "ft", "with"]
exceptions = ["MiyaGi & Эндшпиль", "AC/DC"]
year_length = 4

[ui]
max_comment_length = 60
search_height = 4   # количество строк от края верхнего.
cava_height = 3     # нижний бар
step_offset = 3     # количество строк под вырез левый.

line_x = 1          # Позиция по горизонтали
line_y = 28         # Позиция по вертикали (на какой высоте рисовать)
line_width = 2      # Длина самой палки

search_box_x = 1
search_box_y = 0
search_box_width = 45
search_box_height = 5

library_x = 4
library_y = 4
library_width = 42
library_height = 36

logo_x = 0
logo_y = 29


[logging]
max_logs = 5