[package]
name = "rap-engine"
version = "0.3.8"
edition = "2024"

[dependencies]
rodio = { version = "0.22.2", features = ["symphonia-all", "symphonia-isomp4"] }
symphonia = { version = "0.5", features = ["all-formats", "all-codecs", "isomp4"] }
opus-codec = "0.1.2"
ogg = "0.9"

tokio.workspace = true